version: "3.9"
services:
  web:
    build: web/
    ports:
      - "80:80"
  words:
    build: words/
  db:
    build: db/
    environment:
      PGDATA: pg
      POSTGERS_USER: postgres
      POSTGRES_PASSWORD: 
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust